/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiket_bed;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Kautsar Quraisy <220605110162@student.uin-malang.ac.id>
 */
public class transfer extends javax.swing.JFrame {

    private String filename;
    public static Connection con;
    public static Statement stm;
    private String paket;
    Corder aa = new Corder();
    Cregister bb = new Cregister();
    private int idUser;

    public String getPaket() {
        return paket;
    }

    public void setPaket(String paket) {
        this.paket = paket;
    }

    /**
     * Creates new form transfer
     *
     * @param idUser
     */
    public transfer(int idUser) {
        this.idUser = idUser;
        initComponents();
        isiComboBox();
        setharga();
    }

    public int getIdUser() {
        return idUser;
    }

    public void isiComboBox() {
        try {
            Corder order = new Corder();
            ResultSet hasilOrder = order.tampilData(getIdUser());
            while (hasilOrder.next()) {
                String idOrder = (hasilOrder.getString("id_order"));
                idOrderjComboBox1.addItem(idOrder);
            }
        } catch (SQLException ex) {
            Logger.getLogger(transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setharga() {
        try {
            String ID = idOrderjComboBox1.getItemAt(idOrderjComboBox1.getSelectedIndex());
            int IDOrder = Integer.parseInt(ID);
            ResultSet hasil = aa.CariData(IDOrder);
            if (hasil.next()) {
                String tanggal = hasil.getString("tanggal");
                String packet = hasil.getString("paket");
                String id_user = hasil.getString("id_user");
                String total = hasil.getString("total");
                int idUserr = Integer.parseInt(id_user);
                ResultSet hasil1 = bb.CariData(idUserr);
                if (hasil1.next()) {
                    String nama = hasil1.getString("nama");
                    detailLabel.setText(nama + " | " + tanggal + " | " + packet);
                }

                hargaLabel.setText("Total Yang Harus Dibayar: " + total);
            }
        } catch (SQLException | NumberFormatException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_foto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        idOrderjComboBox1 = new javax.swing.JComboBox<>();
        hargaLabel = new javax.swing.JLabel();
        detailLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/contohNota.jpg"))); // NOI18N
        getContentPane().add(label_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 340, 210));

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 80, 40));

        idOrderjComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idOrderjComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(idOrderjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 384, 220, 30));

        hargaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        hargaLabel.setForeground(new java.awt.Color(255, 255, 255));
        hargaLabel.setText("Jumlah Yang Harus Dibayar : Rp.200.000");
        getContentPane().add(hargaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        detailLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        detailLabel.setForeground(new java.awt.Color(255, 255, 255));
        detailLabel.setText("DD-MM-YYYY | Paket 1");
        getContentPane().add(detailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bed5.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int idOrder = Integer.parseInt(idOrderjComboBox1.getItemAt(idOrderjComboBox1.getSelectedIndex()));
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image img = icon.getImage().getScaledInstance(label_foto.getWidth(), label_foto.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon ic = new ImageIcon(img);
            label_foto.setIcon(ic);
            this.filename = f.getAbsolutePath();

            String newpath = "src/upload";
            File directory = new File(newpath);
            if (!directory.exists()) {
                directory.mkdirs();
            }
            File fileawal = null;
            File fileakhir = null;
            String ext = this.filename.substring(filename.lastIndexOf(".") + 1);
            fileawal = new File(filename);
            fileakhir = new File(newpath + "/" + idOrderjComboBox1.getItemAt(idOrderjComboBox1.getSelectedIndex()) + "." + ext);

            aa.uploadBukti(idOrder, fileakhir.toString());
            Files.copy(fileawal.toPath(), fileakhir.toPath(), StandardCopyOption.REPLACE_EXISTING);

// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idOrderjComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idOrderjComboBox1ItemStateChanged
        setharga();        // TODO add your handling code here:
    }//GEN-LAST:event_idOrderjComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        home hm = new home(getIdUser());
        hm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            login loginFrame = new login();
            loginFrame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailLabel;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JComboBox<String> idOrderjComboBox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_foto;
    // End of variables declaration//GEN-END:variables
}
